# =============================================================================
# NB_01_SETUP.py
# Creates all Delta tables needed for the governance system.
# Seeds rule catalog with rules derived from actual data model.
# Run once. Safe to re-run — uses CREATE IF NOT EXISTS.
# No shortcuts prefix on source tables (Fabric Shortcuts limitation).
# =============================================================================

# CELL 1 — Spark session
# -----------------------------------------------------------------------------
from pyspark.sql import SparkSession
from pyspark.sql.types import *
import pyspark.sql.functions as F

spark = SparkSession.builder.getOrCreate()
spark.sql("SET spark.sql.ansi.enabled = false")
print("Spark ready.")


# CELL 2 — dq_rule
# Business team owns content. IT team owns table.
# rule_code is the machine key used in notebook dispatch.
# -----------------------------------------------------------------------------
spark.sql("""
CREATE TABLE IF NOT EXISTS dq_rule (
    rule_id          INT,
    rule_code        STRING,
    rule_name        STRING,
    category         STRING,     -- 'CASE' | 'INVOICE' | 'CAPACITY'
    description      STRING,
    applies_table    STRING,     -- 'Prosesser' | 'Fakturalinjer' etc.
    severity         STRING,     -- 'Error' | 'Warning'
    active_flag      BOOLEAN,
    owner_team       STRING,
    rule_version     INT,
    effective_from   DATE,
    effective_to     DATE,       -- NULL = still active
    generated_sql    STRING,     -- frozen SQL condition, generated by AI once
    alert_template   STRING      -- Norwegian message template shown to handler
)
USING DELTA
""")
print("dq_rule ready.")


# CELL 3 — dq_rule_param
# Parameters per rule per scope. Business team edits these.
# Changing a threshold = updating param_value here, never touching notebooks.
# -----------------------------------------------------------------------------
spark.sql("""
CREATE TABLE IF NOT EXISTS dq_rule_param (
    rule_id        INT,
    rule_version   INT,
    scope_type     STRING,   -- 'INDIKATOR' | 'ENHET' | 'GLOBAL'
    scope_key      STRING,   -- e.g. 'Byggesak 3 uker' | '*'
    param_name     STRING,   -- e.g. 'max_days_to_tidligbehandling'
    param_type     STRING,   -- 'INT' | 'BOOL' | 'STRING'
    param_value    STRING,
    default_value  STRING
)
USING DELTA
""")
print("dq_rule_param ready.")


# CELL 4 — dq_alert
# Written by detection notebooks. Read by Power BI and escalation notebook.
# Never written by humans directly.
# Scope: case quality alerts and invoice alerts.
# -----------------------------------------------------------------------------
spark.sql("""
CREATE TABLE IF NOT EXISTS dq_alert (
    alert_id             STRING,     -- SHA2(alert_hash | rule_id) deterministic surrogate
    alert_hash           STRING,
    rule_id              INT,
    rule_code            STRING,
    rule_version         INT,
    category             STRING,
    prosess_id           BIGINT,
    saksnummer           STRING,
    indikator            STRING,
    enhets_id            BIGINT,
    enhet_navn           STRING,
    saksbehandler_kode   STRING,
    saksbehandler_navn   STRING,
    severity             STRING,
    alert_message        STRING,
    detected_at          TIMESTAMP,
    first_detected_at    TIMESTAMP,
    batch_id             STRING,
    status               STRING,
    resolved_at          TIMESTAMP,
    resolved_method      STRING
)
USING DELTA
""")
print("dq_alert ready.")


# CELL 5 — capacity_risk_signal
# Written nightly by nb_03_capacity.
# One row per unit per week. Tracks production rate trend.
# Used by Power BI business team page for capacity ceiling detection.
# -----------------------------------------------------------------------------
spark.sql("""
CREATE TABLE IF NOT EXISTS capacity_risk_signal (
    signal_id            STRING,     -- SHA2(enhets_id | uke_dato | batch_id) deterministic surrogate
    enhets_id            BIGINT,
    enhet_navn           STRING,
    seksjon_navn         STRING,
    avdeling_navn        STRING,
    uke_dato             DATE,        -- Monday of the week
    mottatt              INT,         -- received this week
    produsert            INT,         -- produced this week
    portefolje           INT,         -- open portfolio at week end
    produksjonsrate      DOUBLE,      -- produsert / mottatt
    portefolje_trend_3u  DOUBLE,      -- portfolio change over 3 weeks
    snitt_behandlingstid DOUBLE,      -- avg days to seneste_stoppmilepael
    snitt_tidlig_dager   DOUBLE,      -- avg days to Tidligbehandling_dato
    pct_innenfor_frist   DOUBLE,      -- % within deadline this week
    risk_level           STRING,      -- 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
    risk_reason          STRING,      -- plain Norwegian explanation
    computed_at          TIMESTAMP,
    batch_id             STRING
)
USING DELTA
""")
print("capacity_risk_signal ready.")


# CELL 6 — gebyr_reference
# Machine-readable version of gebyrforskriften.
# Used by invoice control notebook.
# -----------------------------------------------------------------------------
spark.sql("""
CREATE TABLE IF NOT EXISTS gebyr_reference (
    varenr                STRING,
    beskrivelse           STRING,
    forskrift_ref         STRING,
    check_type            STRING,    -- 'EXACT' | 'MIN' | 'COMPONENT' | 'FORBIDDEN'
    expected_amount       DOUBLE,
    min_amount            DOUBLE,
    applies_vedtakstype   STRING,    -- pipe-separated or NULL
    applies_sakstype      STRING,    -- pipe-separated or NULL
    forbidden_vedtakstype STRING,
    valid_from            DATE,
    valid_to              DATE
)
USING DELTA
""")
print("gebyr_reference ready.")


# CELL 7 — Seed dq_rule catalog
# Rules derived from actual data model and governance requirements.
# AI generated the SQL conditions. Human reviewed. Now frozen.
# -----------------------------------------------------------------------------
spark.sql("DELETE FROM dq_rule")

from datetime import date
today = str(date.today())

rules = [
    # ── CASE QUALITY RULES ───────────────────────────────────────────────────

    # Rule 1: Tidligbehandling missing on active process
    # Active = received but not yet produced, case not avsluttet
    (1, "TIDLIG_MANGLER",
     "Tidligbehandling mangler på aktiv prosess",
     "CASE",
     "Prosessen har mottatt søknad men Tidligbehandling_dato er ikke registrert "
     "etter 4 uker. Saksbehandler skal sende mangelbrev eller fatte vedtak innen 28 dager.",
     "Prosesser", "Warning", True, "case-operations", 1, today, None,
     """p.tidligste_startmilepael_dato IS NOT NULL
        AND p.seneste_stoppmilepael_dato IS NULL
        AND p.Tidligbehandling_dato IS NULL
        AND DATEDIFF(CURRENT_DATE(), p.tidligste_startmilepael_dato) > 28
        AND s.Status <> 'Saken er avsluttet'
        AND p.Delprosess_navn NOT IN (
            'Planinitiativ (oppstartsfase før RIPP)',
            'Planskisse (dialogfase før RIPP)'
        )""",
     "Saken ble mottatt {mottatt_dager} dager siden. "
     "Tidligbehandling er ikke registrert. "
     "Fristen er 28 dager fra mottak."),

    # Rule 2: Tidligbehandling deadline exceeded (> 28 days and registered late)
    (2, "TIDLIG_FRIST_BRUTT",
     "4-ukersfrist for tidligbehandling brutt",
     "CASE",
     "Tidligbehandling ble registrert etter 28-dagersfristen fra mottaksdato.",
     "Prosesser", "Error", True, "case-operations", 1, today, None,
     """p.Tidligbehandling_dato IS NOT NULL
        AND p.tidligste_startmilepael_dato IS NOT NULL
        AND DATEDIFF(p.Tidligbehandling_dato, p.tidligste_startmilepael_dato) > 28""",
     "Tidligbehandling ble utført {tidlig_dager} dager etter mottak. "
     "Fristen er 28 dager."),

    # Rule 3: Process has been open very long without production
    # Threshold: 365 days — parameterized by indicator
    (3, "LANG_LIGGETID",
     "Prosessen har ligget ubehandlet uforholdsmessig lenge",
     "CASE",
     "Prosessen har vært åpen lenger enn tillatt for denne indikatoren "
     "uten at seneste_stoppmilepael_dato er satt.",
     "Prosesser", "Warning", True, "case-operations", 1, today, None,
     """p.tidligste_startmilepael_dato IS NOT NULL
        AND p.seneste_stoppmilepael_dato IS NULL
        AND s.Status <> 'Saken er avsluttet'
        AND DATEDIFF(CURRENT_DATE(), p.tidligste_startmilepael_dato)
            > COALESCE(
                (SELECT CAST(param_value AS INT)
                 FROM dq_rule_param rp
                 WHERE rp.rule_id = 3
                 AND rp.scope_key = p.Indikator
                 AND rp.param_name = 'max_open_days'
                 LIMIT 1),
                (SELECT CAST(default_value AS INT)
                 FROM dq_rule_param rp
                 WHERE rp.rule_id = 3
                 AND rp.scope_type = 'GLOBAL'
                 AND rp.param_name = 'max_open_days'
                 LIMIT 1)
              )
        AND p.Delprosess_navn NOT IN (
            'Planinitiativ (oppstartsfase før RIPP)',
            'Planskisse (dialogfase før RIPP)'
        )""",
     "Prosessen har vært åpen i {aapen_dager} dager uten at den er ferdigbehandlet."),

    # Rule 4: Mangelfull case open too long without progress
    (4, "MANGELFULL_LANG_VENTETID",
     "Mangelfull prosess har ventet lenge på komplett dokumentasjon",
     "CASE",
     "Prosessen er markert som mangelfull og har ventet mer enn 90 dager "
     "uten at komplett dokumentasjon er mottatt eller saken er avsluttet.",
     "Prosesser", "Warning", True, "case-operations", 1, today, None,
     """p.Er_mangelfull = 1
        AND p.seneste_stoppmilepael_dato IS NULL
        AND s.Status <> 'Saken er avsluttet'
        AND DATEDIFF(CURRENT_DATE(), p.tidligste_startmilepael_dato) > 90""",
     "Prosessen er mangelfull og har ventet {aapen_dager} dager. "
     "Vurder om saken skal avsluttes eller følges opp aktivt."),

    # ── INVOICE RULES ────────────────────────────────────────────────────────

    # Rule 5: Invoice line amount does not match gebyrforskrift exact fee
    (5, "FAKTURA_AVVIK_EKSAKT",
     "Fakturabeløp avviker fra fastsatt gebyr i forskriften",
     "INVOICE",
     "En fakturalinje har et beløp som ikke stemmer med det faste gebyret "
     "i gebyrforskriften for dette varenummeret.",
     "Fakturalinjer", "Error", True, "case-operations", 1, today, None,
     """fl.Produktnr IS NOT NULL
        AND gr.check_type = 'EXACT'
        AND ABS(fl.Linje_belop - gr.expected_amount) > 1""",
     "Fakturalinje {varenr}: fakturert kr {fakturert}, "
     "forventet kr {forventet} iht. {forskrift_ref}."),

    # Rule 6: Invoice amount below minimum floor for case type
    (6, "FAKTURA_UNDER_MINIMUM",
     "Fakturabeløp er under laveste mulige gebyr for sakstypen",
     "INVOICE",
     "Fakturalinjens beløp er under minimumssatsen for denne typen gebyr, "
     "uavhengig av størrelse eller areal.",
     "Fakturalinjer", "Warning", True, "case-operations", 1, today, None,
     """fl.Produktnr IS NOT NULL
        AND gr.check_type = 'MIN'
        AND fl.Linje_belop < gr.min_amount""",
     "Fakturalinje {varenr}: fakturert kr {fakturert}, "
     "minimum mulig er kr {minimum} iht. {forskrift_ref}."),

    # Rule 7: Tapt_gebyr is non-zero — fee was lost due to deadline breach
    (7, "TAPT_GEBYR",
     "Gebyr tapt som følge av fristoverskridelse",
     "INVOICE",
     "Fakturalinjen har Tapt_gebyr > 0, som betyr at kommunen har mistet "
     "inntekt fordi saksfristen ble overskredet.",
     "Fakturalinjer", "Warning", True, "case-operations", 1, today, None,
     """fl.Tapt_gebyr IS NOT NULL AND fl.Tapt_gebyr > 0""",
     "Tapt gebyr på kr {tapt_gebyr} registrert. "
     "Årsak: fristoverskridelse på prosess {prosess_id}."),
]

rule_schema = StructType([
    StructField("rule_id",       IntegerType(), False),
    StructField("rule_code",     StringType(),  False),
    StructField("rule_name",     StringType(),  False),
    StructField("category",      StringType(),  False),
    StructField("description",   StringType(),  False),
    StructField("applies_table", StringType(),  False),
    StructField("severity",      StringType(),  False),
    StructField("active_flag",   BooleanType(), False),
    StructField("owner_team",    StringType(),  False),
    StructField("rule_version",  IntegerType(), False),
    StructField("effective_from",StringType(),  False),
    StructField("effective_to",  StringType(),  True),
    StructField("generated_sql", StringType(),  True),
    StructField("alert_template",StringType(),  True),
])

(spark.createDataFrame(rules, schema=rule_schema)
 .withColumn("effective_from", F.to_date("effective_from"))
 .withColumn("effective_to",   F.to_date("effective_to"))
 .write.mode("append").saveAsTable("dq_rule"))

print(f"dq_rule seeded: {len(rules)} rules.")


# CELL 8 — Seed dq_rule_param
# Thresholds per rule per indicator. Business team edits these.
# When a regulation changes, only these rows change — not the SQL.
# -----------------------------------------------------------------------------
spark.sql("DELETE FROM dq_rule_param")

params = [
    # Rule 3 — max open days per indicator
    # Byggesak 3 uker: shorter deadline
    (3, 1, "INDIKATOR", "Byggesak 3 uker",             "max_open_days", "INT", "84",  "365"),
    (3, 1, "INDIKATOR", "Byggesak 12 uker",            "max_open_days", "INT", "180", "365"),
    (3, 1, "INDIKATOR", "Byggesak uten frist",         "max_open_days", "INT", "730", "365"),
    (3, 1, "INDIKATOR", "Delesak 3 uker",              "max_open_days", "INT", "84",  "365"),
    (3, 1, "INDIKATOR", "Delesak 12 uker",             "max_open_days", "INT", "180", "365"),
    (3, 1, "INDIKATOR", "Igangsettingstillatelse",     "max_open_days", "INT", "180", "365"),
    (3, 1, "INDIKATOR", "Brukstillatelse",             "max_open_days", "INT", "180", "365"),
    (3, 1, "INDIKATOR", "Ferdigattest",                "max_open_days", "INT", "365", "365"),
    (3, 1, "INDIKATOR", "Seksjonering",                "max_open_days", "INT", "180", "365"),
    (3, 1, "INDIKATOR", "Oppmåling",                   "max_open_days", "INT", "180", "365"),
    (3, 1, "INDIKATOR", "Endringstillatelse",          "max_open_days", "INT", "180", "365"),
    # Plansak indicators get much longer thresholds
    (3, 1, "INDIKATOR", "Offentlig ettersyn privat plan","max_open_days","INT","730", "365"),
    (3, 1, "INDIKATOR", "Dialogfase 1",                "max_open_days", "INT", "365", "365"),
    (3, 1, "INDIKATOR", "Til politisk behandling",     "max_open_days", "INT", "365", "365"),
    # Tilsyn
    (3, 1, "INDIKATOR", "Tilsyn",                      "max_open_days", "INT", "365", "365"),
    (3, 1, "INDIKATOR", "Ulovlighet",                  "max_open_days", "INT", "730", "365"),
    # Global default for any indicator not listed above
    (3, 1, "GLOBAL",    "*",                           "max_open_days", "INT", "365", "365"),
]

param_schema = StructType([
    StructField("rule_id",      IntegerType(), False),
    StructField("rule_version", IntegerType(), False),
    StructField("scope_type",   StringType(),  False),
    StructField("scope_key",    StringType(),  False),
    StructField("param_name",   StringType(),  False),
    StructField("param_type",   StringType(),  False),
    StructField("param_value",  StringType(),  False),
    StructField("default_value",StringType(),  False),
])

(spark.createDataFrame(params, schema=param_schema)
 .write.mode("append").saveAsTable("dq_rule_param"))

print(f"dq_rule_param seeded: {len(params)} parameter rows.")


# CELL 9 — Seed gebyr_reference (gebyrforskriften 2026)
# Fixed-fee items where we can verify exactly.
# -----------------------------------------------------------------------------
spark.sql("DELETE FROM gebyr_reference")

gref = [
    # Grunngebyr §3-2
    ("6321",  "Grunngebyr elektronisk",          "§3-2-1",  "EXACT", 2250.0, None,  None, "Byggesak", None),
    ("6322",  "Grunngebyr papir/e-post",          "§3-2-2",  "EXACT", 3760.0, None,  None, "Byggesak", None),
    # Administrasjonsgebyr — only on andregangsvedtak
    ("6323",  "Administrasjonsgebyr",             "§3-2-3",  "EXACT", 1500.0, None,
     "Igangsettingstillatelse|Brukstillatelse|Ferdigattest", "Byggesak", None),
    ("6323",  "Administrasjonsgebyr forbudt",     "§3-2-3",  "FORBIDDEN", None, None,
     None, None, "Rammetillatelse|Byggesak 12 uker"),
    # Andregangsvedtak §3-9
    ("63911", "IGT nr. 2+",                       "§3-9-1-1","EXACT", 4500.0, None,
     "Igangsettingstillatelse", "Byggesak", None),
    ("63912", "Midlertidig brukstillatelse",      "§3-9-1-2","EXACT", 4500.0, None,
     "Brukstillatelse", "Byggesak", None),
    ("63913", "Ferdigattest etter 5 år",          "§3-9-1-3","EXACT", 7500.0, None,
     "Ferdigattest", "Byggesak", None),
    # Delesak grunngebyr §6-2
    ("6621",  "Grunngebyr fradeling eiendom",     "§6-2-1",  "EXACT", 34290.0, None, None, "Delesak", None),
    ("6623",  "Grunngebyr arealoverføring",       "§6-2-3",  "EXACT", 18180.0, None, None, "Delesak", None),
    ("6624",  "Grunngebyr fradeling anleggseiendom","§6-2-4","EXACT", 67560.0, None, None, "Delesak", None),
    # Tilleggsgebyrer §3-10
    ("63101", "Unntak tekniske krav",             "§3-10-1", "EXACT", 15010.0, None, None, "Byggesak", None),
    ("63102", "Dispensasjon lov/forskrift",       "§3-10-2", "EXACT", 15010.0, None, None, "Byggesak", None),
    ("63103", "Dispensasjon reguleringsplan",     "§3-10-3", "EXACT", 15010.0, None, None, "Byggesak", None),
    ("63104", "Dispensasjon rekkefølgekrav",      "§3-10-4", "EXACT", 18020.0, None, None, "Byggesak", None),
    ("63106", "Dispensasjon 100-metersbeltet",    "§3-10-6", "EXACT", 18020.0, None, None, "Byggesak", None),
    # Minimum floors §3-7 (no BRA available — floor check only)
    ("63711", "Bolig <=4 boenheter (min)",        "§3-7-1",  "MIN",  None, 30040.0,
     "Byggesak 12 uker", "Byggesak", None),
    ("63721", "Boligbygg >4 boenheter (min)",     "§3-7-2",  "MIN",  None, 65700.0,
     "Byggesak 12 uker", "Byggesak", None),
]

gref_schema = StructType([
    StructField("varenr",                StringType(), False),
    StructField("beskrivelse",           StringType(), False),
    StructField("forskrift_ref",         StringType(), False),
    StructField("check_type",            StringType(), False),
    StructField("expected_amount",       DoubleType(), True),
    StructField("min_amount",            DoubleType(), True),
    StructField("applies_vedtakstype",   StringType(), True),
    StructField("applies_sakstype",      StringType(), True),
    StructField("forbidden_vedtakstype", StringType(), True),
])

(spark.createDataFrame(gref, schema=gref_schema)
 .withColumn("valid_from", F.to_date(F.lit(today)))
 .withColumn("valid_to",   F.lit(None).cast(DateType()))
 .write.mode("append").saveAsTable("gebyr_reference"))

print(f"gebyr_reference seeded: {len(gref)} rows.")
print("\n=== SETUP COMPLETE ===")
print("Delta tables: dq_rule, dq_rule_param, dq_alert, "
      "capacity_risk_signal, gebyr_reference")
